#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Random Forest Evaluation with Fixed Best Parameters
=====================================================

This script evaluates Random Forest models using pre-determined optimal parameters
across multiple scaffold splits. It collects statistics across different random seeds
to provide robust performance estimates.

Features:
- Load best parameters from JSON files (generated by bayes_rf.py)
- Multiple scaffold splits with different seeds
- Accept only splits within tolerance of target train/test ratio
- Support for regression and classification tasks
- Support for multi-task datasets

Usage:
    # Regression task
    python evaluate_rf.py --dataset esol --descriptor esol_nsc500_sl20.pkl --params params_measured_log_sol.json

    # Classification task
    python evaluate_rf.py --dataset bace --descriptor bace_nsc500_sl20.pkl --params params_Class.json

    # Multi-task with auto params detection
    python evaluate_rf.py --dataset tox21 --descriptor tox21_nsc500_sl20.pkl --auto-params
"""

import os
import sys
import json
import math
import pickle
import random
import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import (
    roc_auc_score, average_precision_score, mean_squared_error,
    mean_absolute_error, r2_score
)


# =============================================================================
# Scaffold Splitting Functions
# =============================================================================

def get_ring_count(smiles: str, max_rings: int = 5) -> int:
    """Get ring count for a SMILES string."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    n_rings = mol.GetRingInfo().NumRings()
    return min(n_rings, max_rings)


def get_scaffold(smiles: str) -> str:
    """Get Murcko scaffold for a SMILES string."""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    return MurckoScaffold.MurckoScaffoldSmiles(mol=mol)


def scaffold_split(df_smiles: pd.DataFrame, frac_train: float, frac_test: float, 
                   seed: int, max_rings: int = 5):
    """
    Perform scaffold-based train/test split.
    
    Parameters
    ----------
    df_smiles : pd.DataFrame
        DataFrame with 'smiles' column
    frac_train : float
        Fraction of data for training
    frac_test : float
        Fraction of data for testing
    seed : int
        Random seed
    max_rings : int
        Maximum ring count to consider
        
    Returns
    -------
    train_idx, test_idx : np.ndarray
        Indices for train and test sets
    """
    rng = random.Random(seed)
    ring_groups = {}
    scaffold_groups = {}

    for i, smi in enumerate(df_smiles["smiles"].values):
        mol = Chem.MolFromSmiles(smi)
        if mol is None:
            continue
        n_rings = get_ring_count(smi, max_rings)
        scaffold = get_scaffold(smi)
        if scaffold is None:
            continue
        ring_groups.setdefault(n_rings, []).append(i)
        scaffold_groups.setdefault(n_rings, {}).setdefault(scaffold, []).append(i)

    print("Ring count distribution:")
    for n_rings, idxs in sorted(ring_groups.items()):
        label = f">={max_rings} rings" if n_rings == max_rings else f"{n_rings} rings"
        print(f"  {label}: {len(idxs)} molecules")

    train_idx, test_idx = [], []
    random_split_layers = {}

    for n_rings, scf_dict in reversed(list(scaffold_groups.items())):
        scf_list = list(scf_dict.keys())

        if len(scf_list) <= 3:
            print(f"Layer {n_rings}: {len(scf_list)} scaffolds too few, using random split.")
            idxs = ring_groups[n_rings]
            random_split_layers[n_rings] = idxs
            rng.shuffle(idxs)
            n_total = len(idxs)
            n_test = round(frac_test * n_total)
            train_idx.extend(idxs[n_test:])
            test_idx.extend(idxs[:n_test])
            continue

        rng.shuffle(scf_list)
        n_total = len(scf_list)
        n_test = round(frac_test * n_total)
        test_scf = scf_list[:n_test]
        train_scf = scf_list[n_test:]

        train_mols, test_mols = [], []
        for s in train_scf:
            train_mols.extend(scf_dict[s])
        for s in test_scf:
            test_mols.extend(scf_dict[s])

        print(f"Layer {n_rings}: {len(train_scf)} scaffolds ({len(train_mols)} mols) train, "
              f"{len(test_scf)} ({len(test_mols)}) test")

        train_idx.extend(train_mols)
        test_idx.extend(test_mols)

    n_train, n_test = len(train_idx), len(test_idx)
    n_total = n_train + n_test
    print(f"\nTotal molecules: {n_total}")
    print(f"Train: {n_train} ({n_train/n_total:.2%})")
    print(f"Test : {n_test} ({n_test/n_total:.2%})")

    # Adjust ratios if deviation > 2%
    target_frac = np.array([frac_train, frac_test])
    current_counts = np.array([len(train_idx), len(test_idx)])
    current_frac = current_counts / current_counts.sum()

    deviation = target_frac - current_frac
    if np.any(np.abs(deviation) > 0.02):
        print("\nAdjusting using random-split layers to fix ratio...")
        all_random_idxs = []
        for idxs in random_split_layers.values():
            all_random_idxs.extend(idxs)
        rng.shuffle(all_random_idxs)

        total = len(train_idx) + len(test_idx)
        target_counts = (target_frac * total).astype(int)

        while len(train_idx) > target_counts[0] and all_random_idxs:
            i = all_random_idxs.pop()
            if i in train_idx:
                train_idx.remove(i)
                test_idx.append(i)

        while len(train_idx) < target_counts[0] and all_random_idxs:
            i = all_random_idxs.pop()
            if i not in train_idx and i not in test_idx:
                train_idx.append(i)

        print(f"After adjustment: Train {len(train_idx)/total:.2%}, Test {len(test_idx)/total:.2%}")

    return np.array(train_idx), np.array(test_idx)


# =============================================================================
# Task Detection
# =============================================================================

def detect_task_type(labels: np.ndarray) -> str:
    """Auto-detect if task is classification or regression."""
    unique_vals = np.unique(labels[~np.isnan(labels)])
    
    if set(unique_vals).issubset({0.0, 1.0, 0, 1}):
        return "classification"
    
    if len(unique_vals) < 10:
        return "classification"
    
    return "regression"


# =============================================================================
# Parameter Loading
# =============================================================================

def load_params(params_file: Path, task_name: str = None):
    """
    Load best parameters from JSON file.
    
    Parameters
    ----------
    params_file : Path
        Path to JSON file with parameters
    task_name : str, optional
        Task name for multi-task datasets
        
    Returns
    -------
    dict
        Parameter dictionary
    """
    if not params_file.exists():
        raise FileNotFoundError(f"Parameters file not found: {params_file}")
    
    with open(params_file, "r", encoding="utf-8") as f:
        params = json.load(f)
    
    return params


def find_params_file(output_dir: Path, task_name: str):
    """Find parameters file for a task."""
    # Try different naming conventions
    candidates = [
        output_dir / f"params_{task_name}.json",
        output_dir / f"params_{task_name.lower()}.json",
        output_dir / f"{task_name}_params.json",
    ]
    
    for candidate in candidates:
        if candidate.exists():
            return candidate
    
    return None


# =============================================================================
# Evaluation Functions
# =============================================================================

def evaluate_classification_single(model, X_test, y_test):
    """Evaluate classification model."""
    pos_idx = int(np.where(model.classes_ == 1)[0][0])
    y_prob = model.predict_proba(X_test)[:, pos_idx]
    auc = roc_auc_score(y_test, y_prob)
    ap = average_precision_score(y_test, y_prob)
    return {"roc_auc": auc, "pr_auc": ap}


def evaluate_regression_single(model, X_test, y_test):
    """Evaluate regression model."""
    y_pred = model.predict(X_test)
    rmse = math.sqrt(mean_squared_error(y_test, y_pred))
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    return {"rmse": rmse, "mae": mae, "r2": r2}


# =============================================================================
# Main Processing
# =============================================================================

def process_task(X_all, y_all, df_smiles, task_name, task_type, params,
                  test_size, tol, n_accept, max_seed_tries, seed_offset):
    """
    Process a single task with fixed parameters across multiple scaffold splits.
    
    Parameters
    ----------
    X_all : np.ndarray
        Feature matrix
    y_all : np.ndarray
        Labels
    df_smiles : pd.DataFrame
        DataFrame with SMILES
    task_name : str
        Name of the task
    task_type : str
        'classification' or 'regression'
    params : dict
        Model parameters
    test_size : float
        Test set fraction
    tol : float
        Tolerance for train ratio
    n_accept : int
        Number of acceptable splits to collect
    max_seed_tries : int
        Maximum number of seeds to try
    seed_offset : int
        Starting seed offset
        
    Returns
    -------
    dict or None
        Results dictionary or None if failed
    """
    target_train_frac = 1 - test_size
    
    # Filter valid samples
    if task_type == "classification":
        valid_mask = np.isin(y_all, [0, 1])
    else:
        valid_mask = ~np.isnan(y_all)
    
    metrics_list = []
    accepted = 0
    seed_cursor = 0
    
    print(f"\n{'='*70}")
    print(f"Task: {task_name} | Type: {task_type}")
    print(f"Target: {n_accept} acceptable splits (tol={tol:.1%})")
    print(f"{'='*70}")
    
    while accepted < n_accept and seed_cursor < max_seed_tries:
        seed = seed_offset + seed_cursor
        print(f"\n--- Try seed {seed} (accepted {accepted}/{n_accept}) ---")
        
        try:
            train_idx, test_idx = scaffold_split(
                df_smiles, 
                frac_train=target_train_frac, 
                frac_test=test_size, 
                seed=seed
            )
        except Exception as e:
            print(f"Scaffold split failed: {e}")
            seed_cursor += 1
            continue
        
        # Check train ratio
        n_train, n_test = len(train_idx), len(test_idx)
        total = n_train + n_test
        train_frac = n_train / total if total > 0 else 0.0
        
        if abs(train_frac - target_train_frac) > tol:
            print(f"Skipped (train frac={train_frac:.2%} not in "
                  f"[{(target_train_frac-tol):.2%}, {(target_train_frac+tol):.2%}])")
            seed_cursor += 1
            continue
        
        # Filter valid samples
        tr_mask = np.zeros_like(valid_mask, dtype=bool)
        te_mask = np.zeros_like(valid_mask, dtype=bool)
        tr_mask[train_idx] = True
        te_mask[test_idx] = True
        
        tr_keep = tr_mask & valid_mask
        te_keep = te_mask & valid_mask
        
        X_tr, y_tr = X_all[tr_keep], y_all[tr_keep]
        X_te, y_te = X_all[te_keep], y_all[te_keep]
        
        # Skip if too few samples or single class
        if X_tr.shape[0] < 20:
            print(f"Skipped (too few training samples: {X_tr.shape[0]})")
            seed_cursor += 1
            continue
        
        if task_type == "classification":
            if np.unique(y_tr).size < 2 or np.unique(y_te).size < 2:
                print(f"Skipped (single class in train or test)")
                seed_cursor += 1
                continue
        
        # Create and train model
        model_params = params.copy()
        model_params["random_state"] = seed
        model_params["n_jobs"] = 1
        
        if task_type == "classification":
            model = RandomForestClassifier(**model_params)
        else:
            model = RandomForestRegressor(**model_params)
        
        model.fit(X_tr, y_tr)
        
        # Evaluate
        if task_type == "classification":
            metrics = evaluate_classification_single(model, X_te, y_te)
            print(f"Accepted (train frac={train_frac:.2%}). "
                  f"AUC={metrics['roc_auc']:.5f}, PR-AUC={metrics['pr_auc']:.5f}")
        else:
            metrics = evaluate_regression_single(model, X_te, y_te)
            print(f"Accepted (train frac={train_frac:.2%}). "
                  f"RMSE={metrics['rmse']:.5f}, MAE={metrics['mae']:.5f}, R2={metrics['r2']:.5f}")
        
        metrics_list.append(metrics)
        accepted += 1
        seed_cursor += 1
    
    if accepted < n_accept:
        print(f"\nWARNING: Only got {accepted}/{n_accept} acceptable splits")
    
    # Aggregate results
    if not metrics_list:
        return None
    
    if task_type == "classification":
        primary_key = "roc_auc"
        agg_metrics = {
            "roc_auc_mean": float(np.mean([m["roc_auc"] for m in metrics_list])),
            "roc_auc_std": float(np.std([m["roc_auc"] for m in metrics_list], ddof=1)) if len(metrics_list) > 1 else 0.0,
            "pr_auc_mean": float(np.mean([m["pr_auc"] for m in metrics_list])),
            "pr_auc_std": float(np.std([m["pr_auc"] for m in metrics_list], ddof=1)) if len(metrics_list) > 1 else 0.0,
        }
    else:
        primary_key = "rmse"
        agg_metrics = {
            "rmse_mean": float(np.mean([m["rmse"] for m in metrics_list])),
            "rmse_std": float(np.std([m["rmse"] for m in metrics_list], ddof=1)) if len(metrics_list) > 1 else 0.0,
            "mae_mean": float(np.mean([m["mae"] for m in metrics_list])),
            "r2_mean": float(np.mean([m["r2"] for m in metrics_list])),
        }
    
    print(f"\n--- {task_name} Summary ---")
    print(f"Accepted splits: {accepted}")
    for k, v in agg_metrics.items():
        print(f"  {k}: {v:.5f}")
    
    return {
        "task": task_name,
        "task_type": task_type,
        "n_accepted": accepted,
        "n_total_tries": seed_cursor,
        **agg_metrics,
        "params": params
    }


def main():
    parser = argparse.ArgumentParser(
        description='Evaluate Random Forest with Fixed Best Parameters',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Regression with explicit params file
  python evaluate_rf.py --dataset esol --descriptor esol_nsc500_sl20.pkl --params params_measured_log_sol.json
  
  # Classification with auto params detection
  python evaluate_rf.py --dataset bace --descriptor bace_nsc500_sl20.pkl --auto-params
  
  # Multi-task dataset
  python evaluate_rf.py --dataset tox21 --descriptor tox21_nsc500_sl20.pkl --auto-params --n-accept 10
"""
    )
    
    parser.add_argument(
        '--dataset',
        type=str,
        required=True,
        help='Dataset name (e.g., esol, bace, tox21)'
    )
    
    parser.add_argument(
        '--descriptor',
        type=str,
        required=True,
        help='Descriptor file name (e.g., esol_nsc500_sl20.pkl)'
    )
    
    parser.add_argument(
        '--params',
        type=str,
        default=None,
        help='Parameters JSON file (for single-task datasets)'
    )
    
    parser.add_argument(
        '--auto-params',
        action='store_true',
        help='Auto-detect params files from results directory'
    )
    
    parser.add_argument(
        '--task-type',
        type=str,
        choices=['auto', 'classification', 'regression'],
        default='auto',
        help='Task type (default: auto-detect)'
    )
    
    parser.add_argument(
        '--n-accept',
        type=int,
        default=10,
        help='Number of acceptable splits to collect (default: 10)'
    )
    
    parser.add_argument(
        '--max-seed-tries',
        type=int,
        default=100,
        help='Maximum number of seeds to try (default: 100)'
    )
    
    parser.add_argument(
        '--seed-offset',
        type=int,
        default=0,
        help='Starting seed offset (default: 0)'
    )
    
    parser.add_argument(
        '--test-size',
        type=float,
        default=0.2,
        help='Test set fraction (default: 0.2)'
    )
    
    parser.add_argument(
        '--tol',
        type=float,
        default=0.02,
        help='Tolerance for train ratio (default: 0.02)'
    )
    
    parser.add_argument(
        '--descriptor-dir',
        type=str,
        default='../calculate_descriptors/descriptors',
        help='Directory containing descriptor files'
    )
    
    parser.add_argument(
        '--data-dir',
        type=str,
        default='../data',
        help='Directory containing label and SMILES files'
    )
    
    parser.add_argument(
        '--params-dir',
        type=str,
        default='results',
        help='Directory containing parameters JSON files'
    )
    
    parser.add_argument(
        '--output-dir',
        type=str,
        default='evaluation_results',
        help='Output directory for evaluation results'
    )
    
    args = parser.parse_args()
    
    # Set paths
    descriptor_dir = Path(args.descriptor_dir)
    data_dir = Path(args.data_dir)
    params_dir = Path(args.params_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Load descriptors
    descriptor_path = descriptor_dir / args.descriptor
    print(f"Loading descriptors: {descriptor_path}")
    with open(descriptor_path, "rb") as f:
        X_all = pickle.load(f)
    print(f"  Shape: {X_all.shape}")
    
    # Load labels
    label_path = data_dir / f"{args.dataset}.csv"
    print(f"Loading labels: {label_path}")
    df_labels = pd.read_csv(label_path)
    if len(df_labels) != X_all.shape[0]:
        raise ValueError(f"Sample mismatch: features={X_all.shape[0]}, labels={len(df_labels)}")
    
    # Get task columns (excluding 'smiles')
    task_cols = list(df_labels.columns)
    if 'smiles' in task_cols:
        task_cols.remove('smiles')
    print(f"  Tasks: {task_cols}")
    
    # Load SMILES for scaffold split
    df_smiles = df_labels.copy()
    if 'smiles' not in df_smiles.columns:
        raise ValueError("Dataset must have 'smiles' column")
    
    # Process each task
    all_results = []
    
    for task in task_cols:
        y_all = df_labels[task].to_numpy()
        
        # Detect or use specified task type
        if args.task_type == 'auto':
            task_type = detect_task_type(y_all)
        else:
            task_type = args.task_type
        
        # Load parameters
        if args.params and len(task_cols) == 1:
            params = load_params(Path(args.params), task)
        elif args.auto_params:
            params_file = find_params_file(params_dir, task)
            if params_file is None:
                print(f"[Warning] No params file found for task '{task}', skipping")
                continue
            params = load_params(params_file, task)
            print(f"Loaded params from: {params_file}")
        else:
            print(f"[Error] No params specified for task '{task}'")
            continue
        
        result = process_task(
            X_all, y_all, df_smiles, task, task_type, params,
            args.test_size, args.tol, args.n_accept, 
            args.max_seed_tries, args.seed_offset
        )
        
        if result is not None:
            all_results.append(result)
    
    # Save summary
    if all_results:
        # Prepare summary DataFrame
        summary_data = []
        for r in all_results:
            row = {
                "task": r["task"],
                "task_type": r["task_type"],
                "n_accepted": r["n_accepted"],
            }
            # Add metrics
            for k, v in r.items():
                if k not in ["task", "task_type", "n_accepted", "n_total_tries", "params"]:
                    row[k] = v
            summary_data.append(row)
        
        df_summary = pd.DataFrame(summary_data)
        
        # Sort by primary metric
        if "roc_auc_mean" in df_summary.columns:
            df_summary.sort_values("roc_auc_mean", ascending=False, inplace=True)
        elif "rmse_mean" in df_summary.columns:
            df_summary.sort_values("rmse_mean", ascending=True, inplace=True)
        
        output_file = output_dir / f"evaluation_{args.dataset}.csv"
        df_summary.to_csv(output_file, index=False)
        
        print(f"\n{'='*70}")
        print(f"EVALUATION SUMMARY")
        print(f"{'='*70}")
        print(f"Results saved to: {output_file}")
        print(f"\nAll tasks:")
        print(df_summary.to_string(index=False))
        
        # Overall statistics
        if "roc_auc_mean" in df_summary.columns:
            overall_mean = df_summary["roc_auc_mean"].mean()
            print(f"\nOverall mean AUC: {overall_mean:.5f}")
        elif "rmse_mean" in df_summary.columns:
            overall_mean = df_summary["rmse_mean"].mean()
            print(f"\nOverall mean RMSE: {overall_mean:.5f}")
    else:
        print("\n[Warning] No tasks were successfully evaluated")


if __name__ == "__main__":
    main()